# Site settings
title: MyBlog
email: srcho01@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Kookmin Univ. Software
  21 Seorim Cho
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: srcho01

# Build settings
markdown: kramdown

paginate: 4

author: Seorim Cho

gems: [jekyll-paginate]
