# General Jekyll Config
highlighter: rouge
url: https://srcho01.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

comment:
  provider:     "disqus"
  disqus:
    shortname:  "srcho01"

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-KSW9DK5PPK"
    anonymize_ip         : # true, false (default)